<a href="https://colab.research.google.com/github/soraidaaaaa/TIL_nlp/blob/master/0804_Hashing_trick.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# 텐서플로와 머신러닝으로 시작하는 자연어 처리 참고

import tensorflow as tf
from tensorflow.keras.preprocessing.text import hashing_trick
from tensorflow.keras.layers import Input, Embedding, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
import numpy as np



In [4]:
samples = ['오늘 하루 좋은날 되십시오',
           '너무 너무 졸린 날이야',
           '오늘 하루 피곤한거 같아',
           '나 좋은 일이 생겼어',
           '내용이 어려워도 힘내서 공부합시다',
           '마지막 문장은 연습용 문장']
labels = [[1],[0],[0],[1],[1],[0]]



In [32]:
# hash 테이플로 문서를 수치화
Vocab_size = 6
sequences = [hashing_trick(s, Vocab_size) for s in samples]
sequences = np.array(sequences)
labels = np.array(labels)
print(sequences)

[[51 62 34 44]
 [33 33 44  9]
 [51 62 60 26]
 [61 31 24 17]
 [35 52 41 15]
 [26 48 54  9]]


In [25]:
# Embedding layer 내부 출력층 개수
Emb_size = 8

In [33]:
# DL Model

xInput = Input(batch_shape=(None, sequences.shape[1]))
embed_input = Embedding(input_dim = Vocab_size + 1, output_dim = Emb_size)(xInput)
embed_input1 = tf.reduce_mean(embed_input, axis=-1)
hidden_layer = Dense(128, activation=tf.nn.relu)(embed_input1)
output = Dense(1, activation='sigmoid')(hidden_layer)

model = Model(xInput, output)
model.compile(loss = 'binary_crossentropy', optimizer=Adam(lr=0.01))



In [34]:
model.fit(sequences, labels, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 1ms/step - loss: 0.6922
Epoch 2/100
1/1 [==============================] - 0s 6ms/step - loss: 0.6853
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6745
Epoch 4/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6607
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6430
Epoch 6/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6211
Epoch 7/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5943
Epoch 8/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5623
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5254
Epoch 10/100
1/1 [==============================] - 0s 2ms/step - loss: 0.4845
Epoch 11/100
1/1 [==============================] - 0s 2ms/step - loss: 0.4399
Epoch 12/100
1/1 [==============================] - 0s 1ms/step - loss: 0.3925
Epoch 13/100
1/1 [==============================] - 0s 1ms/st

In [35]:
pred = model.predict(sequences)
print(np.round(pred, 0))

[[1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]]
